### ISSUE TITLE
安装目录选取问题

### ISSUE THREAD

**Issue by UbeCc** [vector-wlc/VSCodeQtConfigure#2]
请问Macos用Homebrew安装的Qt6.4，安装目录应该长什么样子呢? ./opt/homebrew/Cellar/qt和/opt/homebrew/Cellar/qt/6.4.3_2都提示路径错误

**Comment by vector-wlc** [comment]
这个插件不支持 MacOS， README 中已经写了 只支持 windows 和 linux

**Comment by UbeCc** [comment]
好的，谢谢！
